### ISSUE TITLE
Is it works?

### ISSUE THREAD

**Issue by hakavlad** [temoto/peacemaker#1]
Hello! Tell me please, how to start it on Debian?

I ran main.go, and get next output:
```
./main.go:54:13: undefined: ProcSource
./main.go:59:13: undefined: ProcSource
./main.go:80:9: victim.Terminate undefined (type *Process has no field or method Terminate)

```

**Comment by temoto** [comment]
It works. Do this:
- `go get github.com/temoto/peacemaker`
- find executable `PATH=$PATH:$(go env GOBIN):$(go env GOPATH)/bin which peacemaker`
> /home/temoto/go/bin/peacemaker

Closest to what you wanted is:

```shell
git clone github.com/temoto/peacemaker
cd ./peacemaker
go get .
go build
./peacemaker  # executable in source directory
```

`go run` is mainly for debugging small one-file programs, you can safely ignore this command until you really need it.

**Comment by hakavlad** [comment]
Thank you!
